### ISSUE TITLE
Issue when loading data into editor

### ISSUE THREAD

**Issue by atulmy** [GoCapsule/tiptap-extensions#5]
With an empty editor, the columns seems to render properly and is editable:
<img width="960" alt="Screenshot 2022-10-13 at 6 06 58 PM" src="https://user-images.githubusercontent.com/685786/195619555-3ccdf54b-8955-4b12-a658-79c326a9a73e.png">

But when loading saved data into editor, it loses the column markup:
<img width="952" alt="Screenshot 2022-10-13 at 6 07 11 PM" src="https://user-images.githubusercontent.com/685786/195619570-9674223d-28ac-47a4-87d5-7908f88731ac.png">

Actual data:
```
<div class="column-block"><div class="column"><p>one</p></div><div class="column"><p>two</p></div></div>
```

What the editor holds:
```
<div contenteditable="true" translate="no" class="ProseMirror" tabindex="0"><p>one</p><p>two</p></div>
```

Any idea what I may be doing wrong?

**Comment by atulmy** [comment]
CC @leonard-henriquez

**Comment by leonard-henriquez** [comment]
@atulmy Yes, i think it is due to the absence of `parseHTML` in the nodes `ColumnBlock` and `Column`.
In my use case I only load content from JSON which works without needing the `parseHTML`.
The tiptap documentation is here: https://tiptap.dev/guide/node-views#parse-html
I'm not sure I will have the time in the next few days to open a PR to support this feature, but I can review one if you write one !

**Comment by atulmy** [comment]
@leonard-henriquez thanks for the reply. Hope this gets resolved soon :)

**Comment by atulmy** [comment]
Thanks for the guidance, was able to make it work by using `<section>` and `<article>` tags.
